// Code generated by 'go generate'; DO NOT EDIT.

package ownerperm

import (
	"syscall"
	"unsafe"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modadvapi32 = syscall.NewLazyDLL("advapi32.dll")

	procConvertStringSecurityDescriptorToSecurityDescriptorW = modadvapi32.NewProc("ConvertStringSecurityDescriptorToSecurityDescriptorW")
	procGetSecurityDescriptorDacl                            = modadvapi32.NewProc("GetSecurityDescriptorDacl")
	procGetSecurityDescriptorOwner                           = modadvapi32.NewProc("GetSecurityDescriptorOwner")
	procSetNamedSecurityInfoW                                = modadvapi32.NewProc("SetNamedSecurityInfoW")
)

func convertStringSecurityDescriptorToSecurityDescriptor(sddl string, revision uint32, sd *uintptr, size *uint32) (err error) {
	var _p0 *uint16
	_p0, err = syscall.UTF16PtrFromString(sddl)
	if err != nil {
		return
	}
	return _convertStringSecurityDescriptorToSecurityDescriptor(_p0, revision, sd, size)
}

func _convertStringSecurityDescriptorToSecurityDescriptor(sddl *uint16, revision uint32, sd *uintptr, size *uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procConvertStringSecurityDescriptorToSecurityDescriptorW.Addr(), uintptr(unsafe.Pointer(sddl)), uintptr(revision), uintptr(unsafe.Pointer(sd)), uintptr(unsafe.Pointer(size)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func getSecurityDescriptorDacl(sd uintptr, present *int32, dacl *uintptr, defaulted *int32) (err error) {
	r1, _, e1 := syscall.SyscallN(procGetSecurityDescriptorDacl.Addr(), uintptr(sd), uintptr(unsafe.Pointer(present)), uintptr(unsafe.Pointer(dacl)), uintptr(unsafe.Pointer(defaulted)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func getSecurityDescriptorOwner(sd uintptr, owner *uintptr, defaulted *int32) (err error) {
	r1, _, e1 := syscall.SyscallN(procGetSecurityDescriptorOwner.Addr(), uintptr(sd), uintptr(unsafe.Pointer(owner)), uintptr(unsafe.Pointer(defaulted)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func setNamedSecurityInfo(name string, objectType uint32, info uint32, owner uintptr, group uintptr, dacl uintptr, sacl uintptr) (ret error) {
	var _p0 *uint16
	_p0, ret = syscall.UTF16PtrFromString(name)
	if ret != nil {
		return
	}
	return _setNamedSecurityInfo(_p0, objectType, info, owner, group, dacl, sacl)
}

func _setNamedSecurityInfo(name *uint16, objectType uint32, info uint32, owner uintptr, group uintptr, dacl uintptr, sacl uintptr) (ret error) {
	r0, _, _ := syscall.SyscallN(procSetNamedSecurityInfoW.Addr(), uintptr(unsafe.Pointer(name)), uintptr(objectType), uintptr(info), uintptr(owner), uintptr(group), uintptr(dacl), uintptr(sacl))
	if r0 != 0 {
		ret = syscall.Errno(r0)
	}
	return
}
