#!/usr/bin/env python3
"""generate-check: every file a `//go:generate` line writes with `-output` is
what that line generates today.

Written for 0010-PLAN P6b: llmprovider/internal/ownerperm's Windows bindings
are generated by mkwinsyscall, and a hand edit of the generated file, or a
declaration changed without regenerating, must fail CI. For each .go file's
(tracked, or new and not ignored) `//go:generate` line that names `-output <file>`, it runs the same
command, in the same directory, with the output sent to a temporary file, and
compares the two byte for byte. The generator's version is the one the line
pins, so there is one place to change it.

Usage:
  scripts/check_generated.py

Exit codes: 0 clean, 1 a check failed, 2 tool error.
"""
from __future__ import annotations

import shlex
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PREFIX = "//go:generate "


def directives() -> list[tuple[Path, list[str]]]:
    """Returns (directory, argv) for each `//go:generate` line with -output."""
    # Tracked and new (not ignored) files, so a package not yet committed is
    # checked too.
    files = subprocess.run(["git", "ls-files", "-co", "--exclude-standard", "*.go"], cwd=ROOT,
                           capture_output=True, text=True, check=True)
    found = []
    for rel in files.stdout.split():
        for line in (ROOT / rel).read_text(encoding="utf-8").splitlines():
            if line.startswith(PREFIX):
                argv = shlex.split(line[len(PREFIX):])
                if "-output" in argv:
                    found.append(((ROOT / rel).parent, argv))
    return found


def main() -> int:
    problems = []
    checked = 0
    for directory, argv in directives():
        at = argv.index("-output")
        if at + 1 >= len(argv):
            print(f"generate-check: {directory}: -output has no file", file=sys.stderr)
            return 2
        target = directory / argv[at + 1]
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / target.name
            cmd = argv[:at + 1] + [str(out)] + argv[at + 2:]
            proc = subprocess.run(cmd, cwd=directory, capture_output=True, text=True, check=False)
            if proc.returncode != 0:
                print(f"generate-check: {' '.join(cmd)} failed:\n{proc.stderr}", file=sys.stderr)
                return 2
            checked += 1
            rel = target.relative_to(ROOT)
            if not target.exists():
                problems.append(f"{rel} is missing; run go generate")
            elif out.read_bytes() != target.read_bytes():
                problems.append(f"{rel} differs from what its //go:generate line produces; run go generate")
    for p in problems:
        print(f"generate-check: {p}")
    print(f"generate-check: {checked} generated file(s), {len(problems)} problem(s)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
